import { type PropsWithChildren } from 'react'
import { type Metadata } from 'next'
import { ColorSchemeScript } from '@mantine/core'
import Providers from '@/app/Providers'
import AppLayout from './components/AppLayout'

import '@mantine/core/styles.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: PropsWithChildren<{}>) => {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
